name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Create appsettings.Production.json
      run: |
        echo '{
          "ConnectionStrings": {
            "DefaultConnection": "Data Source=/app/data/KatalonScheduler.db",
            "HangfireConnection": "Data Source=/app/data/KatalonScheduler.Hangfire.db"
          },
          "Katalon": {
            "ApiKey": "${{ secrets.KATALON_API_KEY }}"
          
          },
          "Git": {
            "AccessToken": "${{ secrets.GIT_ACCESS_TOKEN }}"
          }
        }' > appsettings.Production.json

##CW fture deployment placholder